services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - NZBGET_USER=nzbget #optional
      - NZBGET_PASS=tegbzn6789 #optional
    volumes:
      - /mnt/user/appdata/nzbget:/config
      - /mnt/user/downloads:/downloads #optional
    ports:
      - 6780:6789
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.entrypoint=websecure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.service.downindrakes.com`)"
      - "traefik.http.routers.radarr.tls.certresolver=le"
      - "traefik.port=6780"
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    name: frontend
    external: true
